### ISSUE TITLE
Tokens for EKS return 401 error

### ISSUE THREAD

**Issue by bbakersc** [mhart/aws4#108]
We are in the process of migrating from vanilla K8S to EKS, and we're having a problem with the generated tokens using the library. Using sample Go and Python code from AWS, we are able to successfully generate and use the tokens to make calls to the EKS API.

This is a sample of the code we're currently using for this.

<pre>
const debug = require('debug')('Tinker');
const aws4 = require('aws4');
const request = require('request');

process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0;

const getEksToken = ({ authUser, authPass, clusterDomain, region }) => {
  debug(`getEksToken(${authUser}, ${clusterDomain}, ${region})`);

  function removePadding(str) {
    while (str.length && str[str.length - 1] === '=') {
      str = str.slice(0, -1);
    }
    return str;
  }

  const cluster = clusterDomain.split('.')[0];

  const request = {
    host: `https://sts.${region}.amazonaws.com`,
    path: '/?Action=GetCallerIdentity&Version=2011-06-15&X-Amz-Expires=60',
    headers: {
      'x-k8s-aws-id': cluster
    },
    service: 'sts',
    region,
    signQuery: true
  };

  const signedRequest = aws4.sign(request, { accessKeyId: authUser, secretAccessKey: authPass });

  const signedUrl = `${signedRequest.host}${signedRequest.path}`;
  // Using a hard-coded signedUrl generated by another language seems to work from this point
  debug(`getEksToken(): signedUrl is `, signedUrl);

  const byteArray = Buffer.from(signedUrl, 'utf8');
  const encoded = removePadding(byteArray.toString('base64'));
  return `k8s-aws-v1.${encoded}`;
};

const token = getEksToken({ authUser: process.env.AWS_ACCESS_KEY, authPass: process.env.AWS_SECRET_KEY, clusterDomain: 'ekstest.mysite.com', region: 'us-east-1'});
debug(`token is %s`, token);

request.get('https://{host}.gr7.us-east-1.eks.amazonaws.com/api', { headers: { authorization: `Bearer ${token}` } },
  (error, response) => {
    if (error) {
      console.error(`error is `, error);
    } else {
      debug(`response body is `, response.body);
      process.exit(0);
    }
  });
</pre>

Also, we can take a signed URL from the Go or Python code, plug it into the above function as the `signedUrl` and let it finish the process, and it works fine. So at this point, it "appears" to be an issue with the signing of the URL. Any ideas, suggestions, would be appreciated if this is indeed not an issue with the library.

**Comment by bbakersc** [comment]
OK, based on some further research, it appears it _could_ be caused by the query parameters not being in alphabetical order, as specified here in Section 3: https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

When compared with the Python and Go examples previously mentioned, they are definitely not in the correct order according to this documentation.

**Comment by mhart** [comment]
Why are you putting `x-k8s-aws-id` in the headers and not the query? Can you point me to the AWS documentation where these STS are documented?

**Comment by mhart** [comment]
Also, I don't think you're URL base64 encoding correctly – for a start, you need to replace `+` and `/` characters (see https://docs.python.org/3/library/base64.html#base64.urlsafe_b64encode for an example), and to be safe, there could be multiple `=` characters at the end, not just one.

**Comment by bbakersc** [comment]
Still looking for further documentation, but this is where we found the Python example: [Kubernetes SIGs](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/README.md), which shows the use of the header. If I take that out and regenerate, the call to the EKS API fails. It needs that to know which EKS cluster to talk to.

As far as the encoding goes, I can look again - but as I mentioned above, I can take the signed URL generated by the example, hard-code that URL into the Node code, encode that, and the call works fine.

**Comment by mhart** [comment]
Do you know what the string representation of the body is that they're using?

I think the best course of action is to determine the canonical string, etc that the example you've linked to is using, and compare it to the canonical string that this library is producing.

Btw, query params are sorted before calculating the signature: https://github.com/mhart/aws4/blob/master/aws4.js#L234

**Comment by dandonovsc** [comment]
Comparing the GO code and following the aw instructions seems like the nodejs code is not correctly encoding the signed string:

https://github.com/aws/aws-sdk-go/blob/34abf397f4b59e6cae12bb41ea75dcc1d0dc25a9/aws/signer/v4/v4.go#L677

The canonical request string should be hashed and hex-encoded:

`CanonicalRequest =
  HTTPRequestMethod + '\n' +
  CanonicalURI + '\n' +
  CanonicalQueryString + '\n' +
  CanonicalHeaders + '\n' +
  SignedHeaders + '\n' +
  HexEncode(Hash(RequestPayload))`

https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

Looks like the here it's been hashed with digest 'hex' instead:

https://github.com/mhart/aws4/blob/44bb96372fe52cd8bded8824730d0d7d81c3fe18/aws4.js#L192

**Comment by mhart** [comment]
I'm pretty sure everything's being signed ok – this library has been battle tested over many many years.

Can I ask why you're doing this?

```js
const signedUrl = `${signedRequest.host}${signedRequest.path}`;
```

That doesn't look like a URL to me – it doesn't have a protocol. Are you sure you don't mean:

```js
const signedUrl = `https://${signedRequest.host}${signedRequest.path}`;
```

**Comment by dandonovsc** [comment]
That code assembles the `host` from the config object `opts` and the signed path. It actually works. 
Here is an example of the generated by `aws4`:

>https://sts.us-east-1.amazonaws.com/?Action=GetCallerIdentity&Version=2011-06-15&X-Amz-Expires=60&X-Amz-Date=20200330T162006Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[REDACTED]%2F20200330%2Fus-east-1%2Fsts%2Faws4_request&X-Amz-SignedHeaders=host%3Bx-k8s-aws-id&X-Amz-Signature=[REDACTED]

Compared to the aws-sdk-go generated url that generates the working base64 encoded token

> https://sts.us-east-1.amazonaws.com/?Action=GetCallerIdentity&Version=2011-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[REDACTED]%2F20200330%2Fus-east-1%2Fsts%2Faws4_request&X-Amz-Date=20200330T161505Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host%3Bx-k8s-aws-id&X-Amz-Signature=[REDACTED]

Both signed urls have the query parameters, the only difference is their order and the signature

**Comment by mhart** [comment]
Oh, you're including the protocol in the host in aws4 options? That's incorrect:

```
host: `https://sts.${region}.amazonaws.com`
```

Should be:

```
host: `sts.${region}.amazonaws.com`
```

**Comment by mhart** [comment]
See the README for examples: https://github.com/mhart/aws4#example

**Comment by mhart** [comment]
(A host is not a URL)

**Comment by dandonovsc** [comment]
That fixed it. Missed that detail. I actually went through the documentation multiple times but the Golang and Py examples misled me passing in the url with the scheme and domain 
Thank you
