### ISSUE TITLE
With body included signature never matches AWS

### ISSUE THREAD

**Issue by Aeolun** [mhart/aws4#120]
I couldn't figure out what why the signatures weren't matching until I made both the AWS library and the aws4 library spit out their base strings at the same time:

aws4 magically adds a Content-Type and Content-Length header when body is defined. AWS doesn't do such a thing:

```
if (request.body && !headers['Content-Type'] && !headers['content-type'])
        headers['Content-Type'] = 'application/x-www-form-urlencoded; charset=utf-8'

if (request.body && !headers['Content-Length'] && !headers['content-length'])
        headers['Content-Length'] = Buffer.byteLength(request.body)
```

**Comment by mhart** [comment]
What AWS service are you having a problem with?

**Comment by mhart** [comment]
@Aeolun which AWS service was this failing with?

**Comment by mhart** [comment]
(this behaviour is documented btw: https://github.com/mhart/aws4#aws4signrequestoptions-credentials )

**Comment by mhart** [comment]
Closing
