### ISSUE TITLE
The path encoding fails on :

### ISSUE THREAD

**Issue by orasimus** [mhart/aws4#14]
Hi! Thanks for the commits regarding the path escaping.

The signing still fails if the path contains a ```:```. It gets transformed into ```%3A``` earlier and then on line 219:

```path.push(encodeRfc3986(querystring.escape(piece))) ```

querystring.escape turns it into ```%253A```.

So signing calls to e.g. http://domain.com/product/foo:123 fails.

**Comment by mhart** [comment]
@orasimus this is actually how the Amazon services work – you can check it yourself if you like.

**Comment by mhart** [comment]
@orasimus – only S3 will decode the querystring before escaping it again – all the other services do not try to decode entities. And because the character `:` is disallowed in a URL, it needs to be percent encoded in the path in the first place.

**Comment by mhart** [comment]
@orasimus You can read more info on it all here: https://github.com/aws/aws-sdk-js/issues/853#issuecomment-167843405

**Comment by mhart** [comment]
@orasimus If you don't wish to have this behaviour because you're testing or using it in your own service, you can use `doNotEncodePath: true` as an option – this is what I do to get it to pass the test suite: https://github.com/mhart/aws4/blob/master/test/fast.js#L542

**Comment by orasimus** [comment]
Thanks for the comment. I tried looking at the code yesterday, but I guess it was too early in the morning as I missed that. :)
