### ISSUE TITLE
Best way to implement outside of Node.JS

### ISSUE THREAD

**Issue by appeality** [mhart/aws4#15]
This looks awesome. What is the best way to implement this outside of Node.JS? Say I simply want to execute the entire signing process in a web page, then pass the signed URL to a proxy (in a SharePoint app), what's the easy way to do that? Any help would be appreciated.

I should add that I have a special case for calling a service that is not an AWS service, but supports AWS V4 signatures.

**Comment by mhart** [comment]
You should be able to do that with browserify or webpack – they should link in the core node.js modules that are needed (like crypto, url and querystring).

For more info see http://browserify.org/ or https://webpack.github.io/ and https://github.com/webpack/node-libs-browser

Let me know if you have any problems!

**Comment by mhart** [comment]
Out of interest, which service is it that you're talking to?

**Comment by appeality** [comment]
Actually, it's an internal application within my company. 

On December 31, 2015, at 3:33 PM, Michael Hart <notifications@github.com> wrote:

Out of interest, which service is it that you're talking to?

**Comment by appeality** [comment]
Thanks!

**Comment by mhart** [comment]
I added an example of how to do this here: https://github.com/mhart/aws4/tree/master/browser

**Comment by appeality** [comment]
Thanks, for that!
