### ISSUE TITLE
Headers to exclude are not excluded from the cannonicalHeaders

### ISSUE THREAD

**Issue by mrawji** [mhart/aws4#157]
When using the "headers to exclude" feature, they are excluded from the "signedHeaders" group, but they aren't excluded from the cannonicalString, and that causes a signature mismatch.

**Comment by Hobart2967** [comment]
+1,  extraHeadersToIgnore is not used at all inside the libs code.

**Comment by Hobart2967** [comment]
Fix: https://github.com/mhart/aws4/pull/158
