### ISSUE TITLE
Explore adding to bower

### ISSUE THREAD

**Issue by mhart** [mhart/aws4#17]
As mentioned in #16 it might be nice for users of bower to have this packaged up. The main con of this is the extra maintainability overhead of managing another package – not to mention all the browser testing that may or may not need to be done to determine compatibility beyond Node.js.

**Comment by tomprogers** [comment]
This module depends on the nodejs `url` module. That will frustrate packaging it for bower. It also means that people developing mobile apps can't use it -- nodejs modules aren't available in e.g. react-native.

I'd love it if this was actually usable outside of the node env.

**Comment by mhart** [comment]
@tomprogers It's definitely usable outside of the node env! Bower isn't the only solution for non-node.js code – both browserify and webpack should have no problem with this at all. See https://github.com/mhart/aws4/issues/15 and https://github.com/mhart/aws4/issues/18 for more details of how people have used it in the browser, etc.

**Comment by darkyen** [comment]
^ +1

**Comment by darkyen** [comment]
You can alternatively generate a standalone package for bower using browserify :dart:

**Comment by kaizhu256** [comment]
+1 for standalone, and removing lru-cache dependency

**Comment by mhart** [comment]
I should mention that while this isn't on bower, there are other projects, like @nisaacson's https://github.com/nisaacson/aws-v4-sign-small that are basically forks of this repo with some slightly modified deps to make it smaller for the browser (I think? There's no attribution on that project, but all the code appears to come from here). If you're having problems getting this repo to browserify, it might be worth checking them out to see if they fit your needs better?

**Comment by tomprogers** [comment]
@mhart That's exactly what I ended up using. Thanks for the link, though. 8)

**Comment by nisaacson** [comment]
@mhart sorry about leaving out the attribution. I added it in version 1.1.1. Thanks for making aws4!

**Comment by mhart** [comment]
@nisaacson no probs, thanks!

**Comment by mhart** [comment]
I've added an example of how to use this module in the browser here: https://github.com/mhart/aws4/tree/master/browser

**Comment by mhart** [comment]
I've also removed the `lru-cache` dependency as of v1.4.0. I'm going to close this for now as I don't think it's worth the ongoing maintenance – and it works fine using browserify/webpack/etc.
