### ISSUE TITLE
make aws4 dependency free by removing lru-cache

### ISSUE THREAD

**Issue by kaizhu256** [mhart/aws4#19]

**Comment by kaizhu256** [comment]
lets keep this package simple : )

**Comment by mhart** [comment]
@kaizhu256 can you explain this a little more? What problems are you having?

**Comment by kaizhu256** [comment]
just an enhancement request to to make aws4 standalone : )  most of the packages i publish have zero npm-dependencies, e.g. electron-lite, fann-lite, istanbul-lite, jslint-lite, phantomjs-lite, slimerjs-lite, utility2.

in long run, i'm hoping aws4 will stay simple, and keep from temptation of adding extra dependencies, unless there's good reason to.

**Comment by mhart** [comment]
The cache adds a huge performance boost by not needing to recalculate HMAC signatures each time, so it's certainly there for a good reason.

I'd consider a PR if you wanted to write your own well-tested LRU cache to include in this project, but `lru-cache` has been working fine so far and it fits the bill perfectly as far as small single-purpose modules go.

**Comment by mhart** [comment]
I've created a small bundled LRU cache util and removed the lru-cache dependency as of v1.4.0

**Comment by kaizhu256** [comment]
+1 woot!
