### ISSUE TITLE
Auth Header Date Expiring And Not Renewing

### ISSUE THREAD

**Issue by yousefcodes** [mhart/aws4#24]
I'm using this project to authorize requests to an API Gateway service we have. There is an issue where the X-Amz-Date is expiring after five minutes, which is expected.  But what is not expected is for the signature to not get renewed.  Subsequent request past the five minute mark are continued to be signed with the expired date, resulting in Signature Expired errors from the service.

**Comment by mhart** [comment]
Can you show me the code you're using?

`getDateTime()` is called every time the request is prepared, so unless you're passing in your own `X-Amz_Date` (or `Date`) headers, or reusing them, I can't really see how this could occur: https://github.com/mhart/aws4/blob/master/aws4.js#L150-L158

**Comment by mhart** [comment]
If you *are* passing in your own X-Amz-Date headers, then aws4 will use them as-is – this is by design. If you want to use the current time, then don't pass in any date headers – aws4 will populate them for you.

**Comment by yousefcodes** [comment]
Hi,

It actually isn't called every time based on what I see here.   I've submitted a Pull Request, let me know what you think.

**Comment by yousefcodes** [comment]
Turned out the be a closure issue in my end, closing this issue now.
