### ISSUE TITLE
Signature for Elasticsearch (es) not properly calculated

### ISSUE THREAD

**Issue by ajcrites** [mhart/aws4#29]
Elasticsearch domains are of the format `<domain>.<region>.es.amazonaws.com`, so it seems that using `service: "es"` does not work since this yields `es.<region>.amazonaws.com` and I get the error:

> Host: es.us-east-1.amazonaws.com. is not in the cert's altnames: DNS:*.us-east-1.es.amazonaws.com

So I change it to use the actual host of my domain instead:

    axios(aws4.sign({
        host: process.env.ES_ENDPOINT,
        method: "post",
        url: `https://${process.env.ES_ENDPOINT}/foobot/foobot`,
        data,
    }))

Now I get this error from AWS http response:

```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/foobot/foobot

host: <ES-HOST>.us-east-1.es.amazonaws.com
x-amz-date:20160726T211903Z
x-amz-security-token:<TOKEN>

host;x-amz-date;x-amz-security-token
<TOKEN>'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20160726T211903Z
20160726/us-east-1/es/aws4_request
<TOKEN>'

**Comment by mhart** [comment]
Support for ElasticSearch was added in #10 and there are tests here:

https://github.com/mhart/aws4/blob/master/test/fast.js#L37-L41

**Comment by mhart** [comment]
Btw, it doesn't look like you've passed the `path` property correctly – this is necessary for Node.js requests: https://nodejs.org/api/http.html#http_http_request_options_callback

**Comment by ajcrites** [comment]
Axios uses `url` rather than `path`.

**Comment by mhart** [comment]
(`url` is not a supported Node.js http client option – but `host` and `path` are, so you can just use them)

**Comment by ajcrites** [comment]
I've also tried adding `path: "/foobot/foobot"` to the options for `aws4.sign`

**Comment by mhart** [comment]
It also looks like you're doing a `POST` but not passing in the `body`? The docs are here: https://github.com/mhart/aws4#more-options

(also, I'd use an uppercase method – `POST` instead of `post` – I'm not sure how AWS handles a lowercase method)

**Comment by ajcrites** [comment]
The body gets passed into axios via `data` (which is defined earlier). This was working before when I had the ES domain open, so I know there is nothing wrong with the request itself.

Updating `method` to `POST` doesn't help.

**Comment by mhart** [comment]
@ajcrites `aws4` doesn't do anything with a `data` property – it needs a `body` property to sign. `aws4` also has nothing to do with axios, so if it's expecting properties that aren't on a normal Node.js http client call, then you'll need to manipulate that yourself.

**Comment by ajcrites** [comment]
Including `body` is what was required. I can just get that from data.

Thanks for the help!

**Comment by mhart** [comment]
No probs, glad you got it to work with your data structure 👍

**Comment by rochdev** [comment]
Why was this closed? Setting the service to `es` still resolves to `es.us-east-1.amazonaws.com`

**Comment by mhart** [comment]
@rochdev it was closed because the signature is calculated correctly

For es you have to set your host explicitly

**Comment by rochdev** [comment]
Still, while it is calculated "correctly", AWS did not abide by their own standard so the generated URL still doesn't work. Would you accept a PR that handles `es` as an exception to the rule so it generates a valid URL?

**Comment by mhart** [comment]
Well for the general es service, all the URLs should be correct:

http://docs.aws.amazon.com/general/latest/gr/rande.html#elasticsearch-service-regions

If any of them aren't being generated correctly, let me know.

For your own individual search cluster, that will have a unique URL, so passing the host in manually is required. I'm not sure what you mean by "the generated URL still doesn't work"? Can you show me the code you're using?

**Comment by rochdev** [comment]
You're right I didn't think about the URL being unique so it's in fact not possible to generate it from the service name.

What I meant was that the URL generated by the library is `es.us-east-1.amazonaws.com` but should be `us-east-1.es.amazonaws.com`. This is however not an issue since as you said the URL needs to be entered manually anyway.

**Comment by mhart** [comment]
@rochdev there are two different ways of talking to Amazon's "ES service" – one is talking to your own cluster, which sounds like what you want to do, which requires custom hostnames – the other is talking to the central API, which does use hosts like `es.us-east-1.amazonaws.com`, etc as I linked to. The URLs generated for those central hosts are correct, so I won't be changing them.

**Comment by rochdev** [comment]
That makes sense. Thank you for the clarification!
