### ISSUE TITLE
AWS API Gateway: Request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by monish001** [mhart/aws4#33]
Getting following response from AWS API Gateway. Things were fine before but now just the host for the service has changed. Just with that change in request, following error has start poping up.

`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n\'GET\n/stage/v1/adproduct/a03e8a66-55e9-4530-968e-921df2ed826c/result\n\ncontent-type:application/json\nhost:example.com\nx-amz-date:20160919T154421Z\n\ncontent-type;host;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b856\`

Any inputs would be super helpful.

CC @chiranjitdutta1985 @ukils

**Comment by mhart** [comment]
The host says "example.com" – is that the actual host you're setting in the header?

If you could show me the code you're using to invoke aws4, that might help

**Comment by monish001** [comment]
1. `example.com` is what I just put. Service/API is for internal use.
2. Sure, here is the code snippet showing the flow of code.
```

    // Context - serverReq is expressJS request param.

  	var request = {
  		url: config.get('baseUrl') + config.get('relativePath'),
  		method: serverReq.method // GET or POST
  	};

  	if(serverReq.method !== 'GET'){
  		request.data = JSON.stringify(serverReq.body);
  	}

    request.host = config.get('baseHost');
    request.baseURL = config.get('baseUrl');
    request.region = config.get('baseRegion');
    request.service = config.get('baseService');
    if(!request.method){
      request.method='POST';
    }

    request.headers = request.headers || {};
    request.headers["Content-Type"] = "application/json";
    if(request.data){
      request.headers['Content-Length'] = request.data.length;
    }

    var signedRequest =   aws4.sign(request, {
      accessKeyId: config.get('awsAccessKeyId'),
      secretAccessKey: config.get('awsSecretAccessKey')
    });

    return axios(signedRequest)
```

**Comment by mhart** [comment]
You don't seem to have a `path` config in there? Are you just querying `/`?

`aws4` supports the standard Node.js http request interface: https://nodejs.org/api/http.html#http_http_request_options_callback

**Comment by mhart** [comment]
Judging from your code, you can probably just try:
```js
request.path = config.get('relativePath')
```

**Comment by mhart** [comment]
Also, it doesn't appear you're adding a `body`, which is also what `aws4` uses (not `data`)

And your calculation for `Content-Length` will be incorrect if you have any utf8 characters in there.

If you pass in a `body`, you don't need to add the `Content-Length` header – `aws4` will calculate it for you: https://github.com/mhart/aws4/blob/master/aws4.js#L116-L117

**Comment by ukils** [comment]
Tried adding 'path' and changed "data" to "body". 
1. "GET" calls are working fine
2. "POST" is giving [Error: read ECONNRESET].

**Comment by mhart** [comment]
@ukils the `ECONNRESET` is a connection error, nothing to do with `aws4` – so it sounds like your signature is correct now

**Comment by mhart** [comment]
@monish001 @ukils any update here? The `ECONNRESET` error isn't related to `aws`, so I'm assuming everything is working?

**Comment by mhart** [comment]
Closing. Let me know if there are any further issues

**Comment by vinaygoel79** [comment]
@mhart @ukils @monish001 @nnarhinen When I hit a request through postman I face the same problem.

I set this in the aws authantication :-
"Access key:- xxxxxxxxxx
Secrete key:-xxxxxxxxxx
Aws region:- ap-south-1
service name:- execute-api"
Can anyone me to solve this problem. Thanks in advance.

while POST i get this error
{ "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/dms/api/v1/filestore/file\n\ncontent-length:29940\ncontent-type:multipart/form-data\nhost:e7ffona9b4.execute-api.ap-south-1.amazonaws.com\nx-amz-date:20170714T111258Z\n\ncontent-length;content-type;host;x-amz-date\n15c77e9022d5c4e9de523e7279515d245695c76115ebabe7517119701f9ae963'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20170714T111258Z\n20170714/ap-south-1/execute-api/aws4_request\nb0e6151f24eb3a4aa5520da442bdafe7625a44ed7c15f3109eeb78eef038a6cd'\n" }

while GET i got this
{ "message": "No method found matching route api/v1/filestore/file for http method GET." }

In the code I did something like this

`
@RestController
@requestmapping(value = "/v1/filestore")
public class FileUploadController {

@Autowired
private IFileStoreService fileStoreService;

@CrossOrigin
@ResponseBody
@RequestMapping(value = "/file/{id}", method = RequestMethod.GET)`
and in application.properties i set
server.contextPath=/api

If I was wrong then please lead me the correct argument and help me to fix this issue
Thanks

**Comment by vvavepacket** [comment]
@vinaygoel79 were u able to solve the issue? I also have a **content-type:multipart/form-data** in the request

**Comment by olgunyldz** [comment]
Hi,

I have two test case:
1 - keyname: **debug22019 -+(.txt** is not working and getting error like _The request signature we calculated does not match the signature you provided. Check your key and signing method._
2 - neyname: **debug22019 -(.txt** is working fine. 

what it might be wrong? 

Regards

**Comment by akramIOT** [comment]
Team, can someone  resolve this issue for  me.

**Comment by akramIOT** [comment]
POSTMAN Version:  v7.18.0

{
    "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/LocationQuery_stage\n\nhost:a5g085p7md.execute-api.us-east-1.amazonaws.com\nx-amz-date:20200211T205529Z\nx-amz-security-token:X-Amz-Security-Token\n\nhost;x-amz-date;x-amz-security-token\n23d10faba2ba9758d06ae91c4508d73b8501462c8792390f1da605cc12a2d787'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20200211T205529Z\n20200211/us-east-1/execute-api/aws4_request\nb0e1c056070f533feff6e3915304e1cf8a0ee73b7f1e873b1b0d413607c3f87a'\n"
}

Doing a HTTPS  POST  & getting error:

Code  below:

import requests

url = "https://a5g085p7md.execute-api.us-east-1.amazonaws.com/LocationQuery_stage"

payload = {'location': '200, 70',
'sensor': '2'}
files = [

]
headers = {
  'Authorization': 'AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXX/20200211/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-date;x-amz-security-token, Signature=e01717a2e53c3aa47bbf37e60ed285d83f2c6c8e3db99e192c83b6ec476ba7cd',
  'Content-Type': 'multipart/form-data; boundary=--------------------------383962268408970604927878'
}

response = requests.request("POST", url, headers=headers, data = payload, files = files)

print(response.text.encode('utf8'))

**Comment by sreelakshmibheema** [comment]
Hi All, I am trying to fetch API data by generating signature in .Net core
Doing a HTTPS POST : Let me know if something needs to be corrected in the code
In The Authorization header if I pass the generated signature from the below code facing the below error:
{
    "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/test%2A/_search\n\ncontent-length:908\ncontent-type:application/json\nhost:test.us-east-1.es.amazonaws.com\nx-amz-date:20230627T065330Z\n\ncontent-length;content-type;host;x-amz-date\n0972308a9a755661cae211fa6743e331495e2b9ff87282625cf5025028c7d4f1'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20230627T065330Z\n20230627/us-east-1/es/aws4_request\n429431b354dcf6785a5fef992ec381db28e72071ffcb53771a4018a9df98fb33'\n"
}

url - I am using api url 

below is the code implementation

 HttpRequestMessage msg = new HttpRequestMessage(HttpMethod.Post,
                   url);

                msg.Headers.Host = msg.RequestUri.Host;

                // Get and save dates ready for further use.
                DateTimeOffset utcNowSaved = DateTimeOffset.UtcNow;
                string amzLongDate = utcNowSaved.ToString("yyyyMMddTHHmmssZ");
                string amzShortDate = utcNowSaved.ToString("yyyyMMdd");
                msg.Content = new StringContent(payload, Encoding.UTF8, "application/json");
                // Add to headers. 
                msg.Headers.Add("x-amz-date", amzLongDate);
                // **************************************************** SIGNING PORTION ****************************************************
//host;x-amz-date Headers to be passed
                var httpMethod = "POST";
                var uri = new Uri(url);

                var endpoint = uri.Host;
                var path = uri.AbsolutePath;
                var queryString = uri.Query.TrimStart('?');
                var headers = "host;x-amz-date";
                var hostHeader = $"host:{endpoint}";
     
                var amzDateHeader = DateTime.UtcNow.ToString("yyyyMMddTHHmmssZ"); // Use the current UTC date/time in the required format

                var canonicalString = $"{httpMethod}\n{path}\n{queryString}\n{hostHeader}\n{amzDateHeader}\n\n{headers}\n{msg.Content}";
             
                Console.WriteLine("Canonical String: " + canonicalString);

                // 1. Create Canonical Request            
                var canonicalRequest = new StringBuilder();
                canonicalRequest.Append(msg.Method + "\n");
                canonicalRequest.Append(string.Join("/", msg.RequestUri.AbsolutePath.Split('/').Select(Uri.EscapeDataString)) + "\n");

                //canonicalRequest.Append(GetCanonicalQueryParams(msg) + "\n"); // Query params to do.

                var headersToBeSigned = new List<string>();
                foreach (var header in msg.Headers.OrderBy(a => a.Key.ToLowerInvariant(), StringComparer.OrdinalIgnoreCase))
                {
                    canonicalRequest.Append(header.Key.ToLowerInvariant());
                    canonicalRequest.Append(":");
                    canonicalRequest.Append(string.Join(",", header.Value.Select(s => s.Trim())));
                    canonicalRequest.Append("\n");
                    headersToBeSigned.Add(header.Key.ToLowerInvariant());
                }
                canonicalRequest.Append("\n");

                var signedHeaders = string.Join(";", headersToBeSigned);
                canonicalRequest.Append(signedHeaders + "\n");
                canonicalRequest.Append(Hash(msg.Content.ReadAsByteArrayAsync().Result)); // Signature for empty body.
                                                                                          

                // 2. String to sign.            
                string stringToSign = "AWS4-HMAC-SHA256" + "\n" + amzLongDate + "\n" + amzShortDate + "/" + awsRegion + "/" + awsServiceName + "/aws4_request" + "\n" + Hash(Encoding.UTF8.GetBytes(canonicalRequest.ToString()));
              
                // 3. Signature with compounded elements.
                var dateKey = HmacSha256(Encoding.UTF8.GetBytes("AWS4" + secretKey), amzShortDate);
                var dateRegionKey = HmacSha256(dateKey, awsRegion);
                var dateRegionServiceKey = HmacSha256(dateRegionKey, awsServiceName);
                var signingKey = HmacSha256(dateRegionServiceKey, "aws4_request");

                var signature = ToHexString(HmacSha256(signingKey, stringToSign.ToString()));

                // **************************************************** END SIGNING PORTION ****************************************************

                // Add the Header to the request.
                var credentialScope = amzShortDate + "/" + awsRegion + "/" + awsServiceName + "/aws4_request";
                msg.Headers.TryAddWithoutValidation("Authorization", "AWS4-HMAC-SHA256 Credential=" + accessKey + "/" + credentialScope + ", SignedHeaders=" + signedHeaders + ", Signature=" + signature);

                return $"AWS4-HMAC-SHA256 Credential={accessKey}/{credentialScope}, SignedHeaders={signedHeaders}, Signature={signature}";
