### ISSUE TITLE
Add support for iot services

### ISSUE THREAD

**Issue by arabold** [mhart/aws4#34]
Hi and thanks a lot (!) for this library. It's super helpful. We've started working with MQTT and AWS' IoT services. In this context we found some limitations in the current version of aws4.

The IoT service knows at least two distinct "`service`" name signatures need to be generated for: `iotdata` and `iotdevicegateway`. However, the host name for both services is always "*.iot.us-east-1.amazonaws.com" (note the `iot`). The magic of `aws4` to build a host name out of a given service name and vice versa fails for this case. I'm using the popular `request` module and that seemingly relies on this magic, failing to properly sign my requests. The protocols for IoT are described here: http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html -- although it misses any hint on the `iotdata` service. 

 I've tried to specify the host name and the service name manually, but without luck.

So finally I've ended up in using `aws4` manually to sign my request options, and then forward that to `request`:

```
    const cred = credentials = new AWS.EnvironmentCredentials("AWS");
    const topic = "my/topic";
    const body = JSON.stringify({ foo: "bar" });
    const opts = {
        sign_version : 4,
        service: "iotdata",
        region: this.region,
        host: "<endpoint>.iot.us-east-1.amazonaws.com"
        path: `/topics/${encodeURIComponent(topic)}?qos=1`,
        body: body,
        headers: {
            "content-type": "application/javascript"
        },
    };
    // sign the request manually here
    aws4.sign(opts, {
        accessKeyId: cred.accessKeyId,
        secretAccessKey: cred.secretAccessKey,
        sessionToken: cred.sessionToken
    });

    // fire it up
    request.post(`https://${opts.host}${opts.path}`, opts, response => { ... }));
```

Though this is probably also a bug in the `request` module, this seems to be something that could be handled in `aws4` by automatically mapping `iotdata` and `iotdevicegateway` to the actual `iot` hostname part and vice versa. `iotdata` is used for MQTT (`<endpoint>.iot.us-east-1.amazonaws.com/topics`) as well as for the device shadows (`<endpoint>.iot.us-east-1.amazonaws.com/things`), `iotdevicegateway` is used for the WebSocket requests (`<endpoint>.iot.us-east-1.amazonaws.com/mqtt`). Any thoughts?

**Comment by mhart** [comment]
I'm afraid the auto mapping just won't work for certain services – in these cases you'll need to manually provide the service (and possibly region) yourself
