### ISSUE TITLE
Consume request results?

### ISSUE THREAD

**Issue by russellday** [mhart/aws4#36]
How can you consume the results of stdout code (below)? Is it possible to put it into a variable and call a function that on .end()? Thanks!
http.request(opts, function(res) { res.pipe(process.stdout) }).end()

**Comment by mhart** [comment]
@russellday yep, definitely! Check out https://nodejs.org/api/http.html#http_http_request_options_callback for an example of how to do this.

**Comment by mhart** [comment]
(the example in https://nodejs.org/api/http.html#http_http_get_options_callback shows JSON parsing – that might be a better one to start with – you can use the same code for `http.get` as you can for `http.request`, just need to call `end` if you're using the latter)

**Comment by russellday** [comment]
I suspected that was the case however, I receive Connection Refused everytime. If I use your request function that does the standard out with the same Options is works no problem. Do you see anything obvious below that I am missing? (actual values substituted)

var opts = {
    service: 'servicename',
    path: '/2014-06-05/route',
    method: 'GET'}

aws4.sign(opts, {accessKeyId: 'x', secretAccessKey: 'y'});

var req = http.get(opts, function(res) {
  console.log('STATUS: ' + res.statusCode);
  console.log('HEADERS: ' + JSON.stringify(res.headers));

  // Buffer the body entirely for processing as a whole.
  var bodyChunks = [];
  res.on('data', function(chunk) {
    // You can process streamed parts here...
    bodyChunks.push(chunk);
  }).on('end', function() {
    var body = Buffer.concat(bodyChunks);
    console.log('BODY: ' + body);
    // ...and/or process the entire body here.
  })
});

req.on('error', function(e) {
  console.log('ERROR: ' + e.message);
});

**Comment by russellday** [comment]
Figured it out.. https not http. Thanks for you help.
