### ISSUE TITLE
Support `AWS_PROFILE` for credential signing

### ISSUE THREAD

**Issue by ajcrites** [mhart/aws4#38]
You should be able to use the `AWS_PROFILE` environment variable to specify a credentials profile to set the access/secret/session information for signing.

**Comment by ajcrites** [comment]
This could be done using the `AWS.SharedIniFileCredentials` class from the SDK but it seems like you want to avoid including that.

**Comment by mhart** [comment]
@ajcrites I'm not sure what you mean by this – that variable is only for choosing a profile from an INI file isn't it?

**Comment by mhart** [comment]
@ajcrites you might be looking for a library that loads credentials – like this: https://github.com/mhart/awscred ?

**Comment by ajcrites** [comment]
@mhart when using the AWS SDK you can run commands like `AWS_PROFILE=non-default node script.js` and it will set the `AWS_ACCESS_KEY` etc. from the ini settings.

**Comment by ajcrites** [comment]
Seems like `awscred` can only load the credentials asynchronously, but `aws4` signing is synchronous so they are incompatible for now.

**Comment by mhart** [comment]
@ajcrites I think you're confusing the two – `aws4` is for signing – `awscred` (and `AWS_PROFILE`) is for loading the credentials that you then use to sign

**Comment by ajcrites** [comment]
What I am suggesting is that `aws4` is updated to get credentials from `AWS_PROFILE`. So say I have a script that does something very simple:

    //index.js
    const signed = aws4(opts);

I can run this with:

    node .

However it won't work without default credentials. I have a non-default profile in `~/.aws/credentials`, so I can do:

    AWS_PROFILE=non-default node .

...however this _still_ doesn't work because `aws4` won't load the credentials from the ini file.

I can do:

    AWS_ACCESS_KEY_ID=blah AWS_SECRET_ACCESS_KEY=blah node .

This _will_ work since those environment variables are supported in `aws4`, but then I have to type them out and expose them to my history. I'd rather just use `AWS_PROFILE`.

**Comment by mhart** [comment]
Right – you're talking about two separate steps there though.

One is fetching credentials, which, if they're not already in your environment, involves I/O – either from a file, or over the network.

The other (which this library is focused on) is signing a request using credentials that have already been fetched.

I'm not going to add support for fetching credentials to this library – it's not what it's for.

But you can use `awscred` with `aws4` to fetch and sign credentials together – I do this myself often, they're very compatible 👍

**Comment by ajcrites** [comment]
I understand, thank you. Yeah the need for I/O to get credentials from the profile wouldn't work for this library.
