### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by leonardobarrientosc** [mhart/aws4#39]
Hello, the request is freezing, simple do nothing: 

var opts = {
   host: config.elasticSearchHostName,
   method: 'GET',
   region: 'eu-west-1',
   service: 'es',
   path: '/calendars/_search',
   headers: {
    'Host': config.elasticSearchHostName,
    'Accept': 'application/json',
    'X-Amz-Date': moment().format()
   },
   body: JSON.stringify({
      query: {
        match_phrase: {
          calendar_flipped_class_id: "/blended/api/v1/class/3723/"
        }
      },
      sort: { calendar_date: { order: "asc" } }
   })
 }

aws4.sign(opts, {
     accessKeyId: config.accessKeyId,
     secretAccessKey: config.secretAccessKey
    }
  );

httpClient.request( opts, function(res) { res.pipe(process.stdout) }).end()

Can you please help me?

**Comment by mhart** [comment]
I'm not sure what you mean by "freezing"? Maybe you need to add some error handling to your request and response?

In any case – I'd remove the `Host` and `X-Amz-Date` headers – `aws4` will add them for you

**Comment by mhart** [comment]
Also, it doesn't make sense to have a `GET` request with a body...?

**Comment by leonardobarrientosc** [comment]
λ ~/Devel/4134-S4O-CHECKIT-FIREBASE-SYNC/ master* node index.js
λ ~/Devel/4134-S4O-CHECKIT-FIREBASE-SYNC/ master*

**Comment by leonardobarrientosc** [comment]
Nothing happened: 

var opts = {
   host: config.elasticSearchHostName,
   method: 'POST',
   region: 'eu-west-1',
   service: 'es',
   path: '/calendars/_search',
   headers: {
    'Accept': 'application/json',
   },
   body: JSON.stringify({
      query: {
        match_phrase: {
          calendar_flipped_class_id: "/blended/api/v1/class/3723/"
        }
      },
      sort: { calendar_date: { order: "asc" } }
   })
 }

 aws4.sign(opts, {
     accessKeyId: config.accessKeyId,
     secretAccessKey: config.secretAccessKey
    }
  );


httpClient.request( opts, function(res) { res.pipe(process.stdout) }).end()

**Comment by mhart** [comment]
But you're not sending the body?

I have a very simple example of how to do that here (see the `request` function): https://github.com/mhart/aws4#more-options

But really it's probably best to read up on the Node.js docs about how the http module works: https://nodejs.org/api/https.html#https_https_request_options_callback

**Comment by mhart** [comment]
In any case, this is not an issue with this library – all `aws4` does is sign the request.

If you can show that the signature is incorrect because of a bug with `aws4`, I'm happy to reopen this.
