### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by daguej** [mhart/aws4#4]
aws4 is broken on Windows because it [calls `path.normalize` on a URL](https://github.com/mhart/aws4/blob/v1.0.0/aws4.js#L183).

Since Windows uses `\` instead of `/` as the path separator, the wrong canonical string is generated and the signature doesn't work.

**Comment by mhart** [comment]
Thanks for finding this! Totally forgot about Windows, you're right.

Should be fixed now, released as v1.0.1 :+1:
