### ISSUE TITLE
S3 upload performance while calculating signature (question)

### ISSUE THREAD

**Issue by matylla** [mhart/aws4#43]
Hi there,

I have the following code working just fine (upload to S3):

````js
const fs = require("fs");
const aws4 = require("aws4");
const https = require("https");

const hash = aws4.sign({
    service: "s3",
    region: "eu-central-1",
    method: "PUT",
    path: "/my-bucket/image.jpg",
    headers: {
        "Content-Type": "image/jpeg"
    },
    body: fs.readFileSync("./image.jpg")
}, {
    accessKeyId: "my-access-key",
    secretAccessKey: "my-secret-key"
});

var req = https.request({
    hostname: "s3-eu-central-1.amazonaws.com",
    port: 443,
    method: "PUT",
    path: "/my-bucket/image.jpg",
    headers: hash.headers
});

fs.createReadStream("./image.jpg").pipe(req);
````

As I understand correctly, the whole file that is being uploaded needs to be added to the signature. What worries me is that line:

````js
body: fs.readFileSync("./image.jpg")
````

What if `image.jpg` is a 500MB file which is loaded into memory just to calculate the signature? Is there any other possibility to upload a file to S3 in a more performant way?

**Comment by mhart** [comment]
Well you'll need to know the total content size (in bytes) either way – but if you know that already (by reading file metadata or similar), then you could create your own version of chunked upload using the steps outlined here:

http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

`aws4` doesn't know anything special about chunked S3 uploads, so you'd need to split the chunks up, etc yourself.

(btw, if you are ok with loading the file into memory, there's no point piping it with a stream – you can just do `req.end(hash.body)`)

**Comment by matylla** [comment]
Can I still use `aws4` to sign individual upload chunks?

**Comment by mhart** [comment]
@matylla you should be able to – although you'll need to figure out exactly what to sign each time (according to that documentation), I haven't added anything special around this. But if you put the correct headers, etc, it should be possible.

Let me know if there's anything in particular that needs to be changed to support it
