### ISSUE TITLE
SupportAPI issue

### ISSUE THREAD

**Issue by kishra1989** [mhart/aws4#49]
Hi,

Am facing an InternalFailure error with the aws4 node.js

The code that am using pretty simple.

var aws4 = require('aws4');
    http = require('request')
var CREDS = {accessKeyId: 'Access_Key',
            secretAccessKey: 'Secret_Key'}

var options = {
            service : 'support',
            method: 'POST',
            headers: {
                        'x-amz-target': 'AWSSupport_20130415.DescribeCases',
                        'content-type': 'application/x-amz-json-1.1'
                      },
            body: '{}'
  };

var sigs = aws4.sign(options, CREDS);
console.log(sigs);
sigs['url'] = 'https://support.us-east-1.amazonaws.com/';

http(options, function (error, response, body) {
            console.log('-------- body --------' + body );
             if (error) throw new Error(error);
});

The error that i get: {"__type":"InternalFailure"}

Can you tell me whats wrong with this code, when I try to use the python version of this code it works fine without any issues.

**Comment by mhart** [comment]
I don't think `InternalFailure` is an issue with `aws4` – normally you'd get some sort of signing error.

I suspect it's something to do with how you're using the request module.

**Comment by kishra1989** [comment]
The issue was with the header and was missing the user-agent field.

**Comment by mhart** [comment]
Ok great, thanks for the update!
