### ISSUE TITLE
Why is this NPM calling out to cloudfront?

### ISSUE THREAD

**Issue by BitHighlander** [mhart/aws4#51]
Was running this repo and this request kept hitting my firewall rules.

54.192.5.251:443
reverse DNS shows this is cloudfront. 

Why would this repo need to call out to cloudfront? This raised a ton of red flags with my system as cloudfront is extremely common in malware.

**Comment by mhart** [comment]
I have no idea what you mean by "running this repo"

Can you explain what you mean?

**Comment by BitHighlander** [comment]
useing this npm.
