### ISSUE TITLE
Calling aws4.sign(requestOptions, creds) never returns

### ISSUE THREAD

**Issue by kebabmane** [mhart/aws4#52]
Hi,

For some reason when I use the following code in onRequest HTTP Interceptor (angular4) the aws4.sign function it doesn't return a signed object and halts the HTTP request

import * as aws4 from 'aws4';

onRequest(requestOptions: RequestOptionsArgs): RequestOptionsArgs {
    console.log('access key:', this.accessKeyId);
    console.log('secert:', this.accessSecret);
    console.log('session token:', this.sessionToken);

    let signedObject = aws4.sign(requestOptions, {
                                       secretAccessKey: this.accessSecret,
                                       accessKeyId: this.accessKeyId,
                                       sessionToken: this.sessionToken,
                                });
    console.log('signed object:', signedObject);

    return requestOptions;
    }

Have confirmed that the access/secret/session tokens all exist but not errors are populated back in the console -  I have also tried with aws4.RequestSigner which has the same response (or lack of)

I have also tried the library in a service as the below code;

    let request = {
      method: 'GET',
      url:    pageUrl,
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
    };
    let opts = {host: url, path: '?size=' + size + '&cursor=' + cursor};

    let signedRequest = aws4.sign(opts, {accessKeyId: this.accessKeyId, secretAccessKey: this.accessSecret, sessionToken: this.sessionToken});
    console.log('signedRequets: ', signedRequest);
    return this._http.get(pageUrl, {headers: signedRequest});

the console log statement never appears and the app doesn't fire off the HTTP GET request and I cannot figure out why

I have other calls working successfully through the signer which DONT have query params at the end, i have tried to set them in the host + path option, both in the host option (single concat string host + path + params) but nothing appears to work

thanks

**Comment by mhart** [comment]
@kebabmane without more information I'm not going to be able to help unfortunately – this appears to be something specific to your setup?

Are you sure there aren't any exceptions being thrown or anything? Perhaps surround it in a try/catch block to check.

**Comment by mhart** [comment]
Closing this – happy to reopen if more detailed information shows a problem with `aws4`
