### ISSUE TITLE
service: 's3' with method put

### ISSUE THREAD

**Issue by kingmayko** [mhart/aws4#53]
Hi, 

I use sdk as below: 
  var opts = {service: 's3', region: 'us-east-1', path: '/xxx/xxx/xxx', method: 'PUT'}
var sign = aws4.sign(opts1, {accessKeyId: AWSAccessKeyId, secretAccessKey: YourSecretAccessKeyID})

But I use postman and set details from JSON.stringify(sign) as below picture, then get error
"The request signature we calculated does not match the signature you provided. Check your key and signing method."

but method:'GET' is work

![image](https://cloud.githubusercontent.com/assets/3955691/26234035/47daedea-3c94-11e7-8cda-f29345670a4e.png)

Does anyone know this problem? 
Please let me know if I mistake the usage.
Thanks very much

**Comment by mhart** [comment]
@kingmayko I'm going to need more information – can you show more code?

**Comment by kingmayko** [comment]
After more test, 
 var opts = {service: 's3', region: 'us-east-1', path: '/xxx/xxx',method:'PUT',
    headers: {
    'Content-Type': 'text/plain'
  },
  body: 'testdata'
}
is work
What I need is find other mechanism to provider the sas generating from server side, and use in client side without presetting body!!

Thanks a lot.

**Comment by kingmayko** [comment]
finally I use aws-sdk
var AWS = require('aws-sdk');
  const params = {
    Bucket: myBucket,
    Key: myKey,
    Expires: 60,
    ContentType: 'image/png',
    ACL: 'public-read'
  }
 AWS.config.update({accessKeyId: AWS_ACCESS_KEY, secretAccessKey: AWS_SECRET_KEY});
  s3.getSignedUrl('putObject', params, function (err, url) {
    console.log('The URL is', url);
  });

and postman and reactjs is work 
![image](https://cloud.githubusercontent.com/assets/3955691/26241460/51fed066-3cb7-11e7-9524-74833d662f2a.png)

**Comment by mhart** [comment]
Glad it works for you 👍
