### ISSUE TITLE
Does not work with create-react-app

### ISSUE THREAD

**Issue by mifi** [mhart/aws4#55]
Same issue as #46:
`TypeError: querystring.unescape is not a function`

But in create-react-app it is not possible to configure bundler (webpack) with aliases. I'm currently using https://github.com/nisaacson/aws-v4-sign-small but it would be nice if `aws4` would work out of the box too.

**Comment by mhart** [comment]
This is a bug with webpack – they really shouldn't be bundling such an old version of querystring – probably best to file a bug over there if you haven't already. If create-react-app can't be configured, then that's a limitation with that library as well, so perhaps file over there too.

**Comment by mhart** [comment]
@mifi I included your commit in the latest version of aws4, published as v1.7.0 – thanks, and hopefully this issue won't pop up anymore!
