### ISSUE TITLE
'matchHost' doesn't work properly in case of some AWS S3 regions

### ISSUE THREAD

**Issue by paulrutter** [mhart/aws4#57]
See the list of hostnames on http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region.
Some regions are only accessible  on a hostname of this form:

> s3-eu-west-1.amazonaws.com
 
This kind of hostnames breaks the 'matchHost' method, as it looks for '.' characters to determine parts of the hostname.
In this case, both the region and the service are tied together as 's3-eu-west-1'.
This breaks functionality as this.service is now no longer 's3' and this.region is 's3-eu-west-1', which is not valid.

As a workaround, both the service and the region can be specified by the calling code, which makes the issue less important. Still, inferring service and region from the URL is not working properly for AWS S3.

**Comment by mhart** [comment]
Unfortunately there are a number of services that this is true for – too many to make exceptions for I fear. As you say, for these services you'll just need to provide the service and region explicitly
