### ISSUE TITLE
Consider rewriting to make use of WebCrypto

### ISSUE THREAD

**Issue by Liath** [mhart/aws4#62]
Swapping node's `crypto` for [calvinmetcalf/native-crypto](https://github.com/calvinmetcalf/native-crypto) would let aws4 seamlessly use the WebCrypto API where it's available (which is [basically everywhere](https://caniuse.com/#feat=cryptography) now). 

There's some [pretty significant performance gains](https://medium.com/@encryb/comparing-performance-of-javascript-cryptography-libraries-42fb138116f3) to be had but aws4 would have to be rewritten to handle the Promises returned by `native-crypto`.
Or if support for older [browsers](https://caniuse.com/#feat=async-functions)/[node](http://node.green/#ES2017-features-async-functions-await) are not a big priotity, it would be real simple to rewrite using `aync`/`await `. Transpiling on publish gets rid of this issue but would require adding a build step, not that much work but still a change.

**Comment by Liath** [comment]
async/await version is literally only a few lines of code changed:

<pre>
diff --git a/aws4.js b/aws4.js
index 0cff0f0..235e740 100644
--- a/aws4.js
+++ b/aws4.js
@@ -1,18 +1,20 @@
 var aws4 = exports,
     url = require('url'),
     querystring = require('querystring'),
-    crypto = require('crypto'),
+    nCrypto = require('native-crypto'),
     lru = require('./lru'),
     credentialsCache = lru(1000)
 
 // http://docs.amazonwebservices.com/general/latest/gr/signature-version-4.html
 
-function hmac(key, string, encoding) {
-  return crypto.createHmac('sha256', key).update(string, 'utf8').digest(encoding)
+async function hmac(key, string, encoding) {
+  var hmac = new nCrypto.Hmac('sha256', key)
+  return await hmac.update(string, 'utf8').digest(encoding)
 }
 
-function hash(string, encoding) {
-  return crypto.createHash('sha256').update(string, 'utf8').digest(encoding)
+async function hash(string, encoding) {
+  var hash = new nCrypto.Hash('sha256')
+  return await hash.update(string, 'utf8').digest(encoding)
 }
</pre>

**Comment by mhart** [comment]
@Liath can you explain why you'd want this? Are you running into performance problems? The hashing is cached, so you should be able to do tens of thousands of sign calls a second.

**Comment by Liath** [comment]
Admittedly, I don't have a good answer for that and I currently making hundreds of reqs/second (through http-aws-es) without a noticeable delay. It just seems like an easy win that might be worth exploring.

**Comment by Liath** [comment]
This was dumb lol, I just get excited about WebCrypto. Closing :)
