### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

### ISSUE THREAD

**Issue by jeremyburton** [mhart/aws4#68]
Having trouble signing a simple GET request using aws4 with axios. I get a CORS error and 403 in the console but digging deeper in the Network tab I see the message "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

``` js
let request = {
  method: 'GET',
  url: 'https://xxxxxxxxxx.execute-api.eu-west-2.amazonaws.com/dev/xxxxxxx',
  path: '/xxxxxxx',
  service: 'execute-api',
  region: 'eu-west-2'
}
let signedRequest = aws4.sign(request, {
  accessKeyId: rootState.auth.accessKeyId,
  secretAccessKey: rootState.auth.secretAccessKey,
  sessionToken: rootState.auth.sessionToken
})
console.log(signedRequest)
delete signedRequest.headers['Host']
axios(signedRequest)
  .then(response => {
    console.log('Status code: ' + response.status)
  })
  .catch(error => {
    return error
  })
```

I'm able to successfully sign a request to the same endpoint using Postman with its AWS Signature authorization type and using the same tokens so I know that the issue isn't related to the tokens.

Have tried to follow the docs. Am I missing something?

**Comment by mhart** [comment]
Not sure – not all that familiar with axois. Have you been able to do it successfully using the builtin Node.js http library as described in the README?

**Comment by mhart** [comment]
Btw, `url` is not a standard property that the Node.js http module accepts. See here for accepted values:

https://nodejs.org/api/http.html#http_http_request_options_callback

**Comment by jeremyburton** [comment]
Thanks for your very quick response. I've just tried the following and I'm getting the same error.

``` js
let request = {
  host: 'xxxxxx.execute-api.eu-west-2.amazonaws.com/dev',
  method: 'GET',
  path: '/xxxxxx',
  service: 'execute-api',
  region: 'eu-west-2'
}
let signedRequest = aws4.sign(request, {
  accessKeyId: rootState.auth.accessKeyId,
  secretAccessKey: rootState.auth.secretAccessKey,
  sessionToken: rootState.auth.sessionToken
})
console.log(signedRequest)
https.request(request, function (res) { res.pipe(process.stdout) }).end()
```
Console error: 
"Failed to load https://xxxxxxx.execute-api.eu-west-2.amazonaws.com/dev/xxxxxx: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled." 

Network message for request:
"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

**Comment by jeremyburton** [comment]
By the way, I'm using the following in my webpack config as you recommended elsewhere. Don't know if that has any significance here?

``` js
resolve: {
      alias: {
        querystring: 'querystring-browser'
      }
    }
```

**Comment by mhart** [comment]
That host doesn't look correct?

**Comment by jeremyburton** [comment]
Yes, I'm trying from the browser. I'm building an SPA with Vue - there is no Node server. 

Can you tell me what looks wrong with host? Axios doesn't require a host to be specified. Is this a requirement of aws4 or of Node.js https module?

Thanks for your help with this. I really appreciate it. I'm stuck for any alternative solution for AWS v4 signature.

**Comment by mhart** [comment]
Your host has a path in it – `/dev` at the end there.

Please read up on the options here:

https://nodejs.org/api/http.html#http_http_request_options_callback

**Comment by jeremyburton** [comment]
Success! As you suggested, fixing the host got this working with the https library. I will now try to get it working with axios and will post again here when I do.

Again, many thanks for your help.

**Comment by mhart** [comment]
No probs, glad you're getting somewhere! 👍

**Comment by alexjfno1** [comment]
@jeremyburton Did you have any luck getting it working with Axios?

**Comment by jeremyburton** [comment]
@alexjfno1 Yes, see [this article](https://medium.com/@joshua.a.kahn/calling-amazon-api-gateway-authenticated-methods-with-axios-and-aws4-6eeda1aa8696) for very useful guidance.

**Comment by shiiyan** [comment]
For someone who see this, `axios` also works fine with `aws4` just like `https`. If you see this error, please double check your `host` `url` `path` `region` `service` in your request options.
