### ISSUE TITLE
Standardise the signing of HTTP requests

### ISSUE THREAD

**Issue by horyd** [mhart/aws4#71]
Hi, I've been struggling with AWSv4 signing with just regular HTTP requests that are hitting my API Gateway service. I think this comes down to the fact that there's no standardization of what goes in and out of the signing functions when this is the case (as compared to when calling an AWS Service).

Would it be possible to utilize the `URL` and `Request` standards here? Such that:

```js
const unsignedRequest = new Request();
const signedRequest = aws4(unsignedRequest, { ...credentials });

/* aws4 */
if (unsignedRequest instanceof Request) {
  const parsedUrl = new URL(unsignedRequest.url)
  /* proceed to use the request and url instances to do
      the signing, eventually returning a Request object */
}
```

Thoughts? I can PR this if the handling is a good idea

**Comment by mhart** [comment]
Closing. Feel free to reopen if passing `host` and `service` didn't solve your issue

**Comment by horyd** [comment]
Yea I fixed the problem I was having by setting `service` equal to `execute-api` and passing the query string into `path`, which I wasn't doing before because I was just putting in [URL.pathname](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/pathname)

Thanks!
