### ISSUE TITLE
put_media on kinesisvideo

### ISSUE THREAD

**Issue by roccomuso** [mhart/aws4#72]
Someone has ever done a PUT_MEDIA request to kinesisvideo using this module?
Right now the method is not available in the official `aws-sdk-js` lib but only the c++ or java ones.

https://github.com/aws/aws-sdk-js/issues/2093

I'm trying to follow this [doc:API_dataplane_PutMedia](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_PutMedia.html), but I'm having a server-side `SerializationException` thrown.

**Comment by mhart** [comment]
A `SerializationException` sounds like you might be getting past the authorization step and you've just got a problem with the payload itself. Like maybe you're missing a header, or passing the data in the wrong format or something

**Comment by roccomuso** [comment]
Yeah probably, but there's no more documentation to follow

**Comment by mhart** [comment]
Closing as unlikely to be related to this library – you'd see an authorization exception if it were

**Comment by MuhammedBeyhanUS** [comment]
hi @roccomuso , sorry to disturb.  I am trying to do the similar thing you tried to do in 2018 which is using putMedia API from a js project. have you managed to do that? Can you lighten me? 
I've found this repo [https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/producer-js/browser-based-ingestion](url) but i think it has some implementation problems. this is the issue i opened [https://github.com/aws-samples/amazon-kinesis-video-streams-demos/issues/143](url). I wonder if you have any source or suggestion. Thanks in advance.

**Comment by roccomuso** [comment]
@MuhammedBeyhanUS I barely remember it, and I'm not sure this is still working (it had some latency issues that I wasn't able to fix), but here's what I've used (it might be broken now due to api changes): https://gist.github.com/roccomuso/e65e80aecbe700db2576e751fa1a22c4

it could be useful to you pheraps
