### ISSUE TITLE
Calculated Signature does not match

### ISSUE THREAD

**Issue by aeronesto** [mhart/aws4#73]
I am using proxy middleware, `http-proxy-middleware`, to secure `es` requests made in the front-end. The route is proxied from a `POST` request to `http://localhost:3001/elasticsearch/<domainname>/_msearch?`. I proxy the request to my `ES_ENDPOINT` defined below. When my aws es cluster has an 'open access domain', the proxy works as long as i don't set the `Authorization` header. If I only set the `Authorization` header, I get the following error: 

`Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header.`

So, I set the `X-Amz-Date` header, and get this error:

`The request signature we calculated does not match the signature you provided.`

I get the same errors when my es cluster has a 'closed access domain' (limited to specific AWS users). The problem does not appear to be with my proxy server, since it works on an `open access [es] domain`. Is there a mistake in my aws4 options, `opts` object, that will cause the signature mismatch?

```js
const express = require('express');
const proxy = require('http-proxy-middleware');
const esProxy = express.Router();
const aws4  = require('aws4');

// define elasticsearch service
const ES_ENDPOINT='search-<domainname>-<domainid>.us-east-1.es.amazonaws.com';

// define options to pass to http-proxy-middleware
const options = {
    target: `https://${ES_ENDPOINT}`, // where to proxy the request
    changeOrigin: true,
    pathRewrite: {
      '^/elasticsearch' : '/', // rewrites '/elasticsearch/<domainname>/_msearch?' to '/<domainname>/_msearch?'
    },
    onProxyReq: (proxyReq, req) => { // proxied
      let body = req.body;
      if (body) {
        if (typeof body === 'object') {
            body = JSON.stringify(body);
        }
      }

      // define aws4 options
      const opts = {
        host: ES_ENDPOINT,
        protocol: 'https:',
        headers: {
          'Content-Type': 'application/json'
        },
        json: true,
        path: '/<domainname>/_msearch?',
        method: 'POST',
        body: body,
    }

      aws4.sign(opts,{accessKeyId: process.env.AWS_ACCESS_KEY_ID, secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY});

      // headers to be used
      const Authorization = opts.headers.Authorization;
      const amzdate = opts.headers['X-Amz-Date'];
      const contentType = opts.headers['Content-Type'];

      // set Headers
      proxyReq.setHeader('X-Amz-Date', amzdate);
      proxyReq.setHeader('Authorization', Authorization);
      proxyReq.setHeader('Content-Type', contentType);

      // set body of proxy
      proxyReq.write(body)

    }
}

// use proxy when route matches /elasticsearch
esProxy.use('/elasticsearch', proxy(options))

module.exports = esProxy;
```

**Comment by mhart** [comment]
I notice you don't have the `service` param – try adding that to opts (with the value `es`)

**Comment by mhart** [comment]
Aside from that (and again, I can't remember off the top of my head whether `aws4` picks that up automatically) – everything looks ok – and I suspect it's something to do with your proxy

**Comment by aeronesto** [comment]
Hi @mhart ,

Thanks for taking the time to investigate. It looks like aws4 does pick up the service automatically. It turns out that the issue was my 'Content-Type'. The `Content-Type` was `application/x-ndjson`, so i just had to make that change in my `opts` object, and now it works:

```js
const opts = {
  host: 'search-<domainname>-<domainid>.us-east-1.es.amazonaws.com',
  headers: {
    'Content-Type': 'application/x-ndjson'
  },
  path: '/<domainname>/_msearch?',
  method: 'POST',
  body: body,
}
```

Thanks again!
