### ISSUE TITLE
"Signature expired" when using aws4 for longer than 5 minutes.

### ISSUE THREAD

**Issue by vfro** [mhart/aws4#78]
I'm getting the following error message when I'm using aws4 for signing AWS URLs for longer than 5 minutes:

```{"message":"Signature expired: 20181010T154931Z is now earlier than 20181010T155002Z (20181010T155502Z - 5 min.)"}```

Scenario:
1. Sign a request without specifying `'Date'` header and `X-Amz-Expires` query parameter.
2. Sleep for 10 minutes.
3. Sign another request without specifying `'Date'` header and `X-Amz-Expires` query parameter.

Expected behavior: The signature is valid, request is accepted by AWS.
Actual behavior: The signature is expired. The request is rejected by AWS with `Signature expired` error message.
Root cause: `RequestSigner.prototype.getDateTime` function creates a new date string and then reuses this string for signing all subsequent requests even after expiration time elapses.
Workaround: Use `headers['Date'] = new Date()` for every request.

**Comment by vfro** [comment]
Yes, you are right. I just found out that I'm reusing the same `headers` object for all the requests. I use lodash `clone` where I should use `cloneDeep`.

I guess the issue is resolved then. Thanks for quick response.

**Comment by greim** [comment]
This seems to be a consequence of mutating user input. I also and ran into this issue. My headers object didn't contain a date, but one was being added and then re-used. This lib could sidestep that by doing something like:

```js
var headers = request.headers = Object.assign({}, request.headers || {})
```

For now I'm working around it by doing something similar in my own code, but it might be nice to add a fix here to avoid this in the future.
