### ISSUE TITLE
how to implement aws4.js in client side application 

### ISSUE THREAD

**Issue by rainnaren** [mhart/aws4#80]
i have been working angularjs application how to implement aws4 in my application

**Comment by monken** [comment]
We recently release https://github.com/emdgroup/aws4-tiny which is based on aws4. You might want to have a look at it.

**Comment by mhart** [comment]
There's a simple browser example here: https://github.com/mhart/aws4/tree/master/browser – you'll need to modify it for your app appropriately, or as @monken says you can use another library
