### ISSUE TITLE
The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by Crasha** [mhart/aws4#83]
I've had a look at similar issues to do with the error I'm having however I believe I have everything I need within the options.

Here is the full error message;

`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

My https request and AWS4 call looks like this;

```
const aws4 = require('aws4');

const postOptions = {
            host: process.env.url,
            path: `/${process.env.env}/api/GetDetails`,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            }
        };

aws4.sign(postOptions);
```

The API endpoint is POST and requires a JSON body to be posted which works fine without AWS_IAM enabled. However, if I enable AWS_IAM and try using the above code, I get the above error.

The Access and Secret aren't specified since this is populated from within Lambda automatically.

I know I haven't included "body" as a property to the postOptions object however I would think with "Method" being set to "POST" there would be no need. I have tried it with "body" and I get the same issue.

Any ideas?

**Comment by mhart** [comment]
You definitely need to include the body, it's part of the signature.

**Comment by mhart** [comment]
What's the endpoint btw? What service are you trying to call?

**Comment by mhart** [comment]
Also, it looks in your snippet like you're using a URL for the host – it should just be a host, not a URL.

**Comment by Crasha** [comment]
Hi,

The process.env.url doesn't include the "https://" or any slashes at the end, it's purely an address.

The endpoint is what the path value is in postOptions.

I'm trying to send a POST request to API Gateway.

Thanks,
Owen

**Comment by mhart** [comment]
Well this library works successfully with API Gateway, so it's almost definitely a problem with your code. It's too hard to tell with the information you've given.

Again, you're not including `body` and you definitely have to.

You can try including `service: 'execute-api'` and `region: '<your region>'` to make sure you're signing with the correct service/region.

Also, how are you using `postOptions` after this? ie, how are you actually making the HTTP request?

**Comment by Crasha** [comment]
Ah, so body did need to be specified... I thought it could be left out since the documentation says "will use 'GET' if not given or 'POST' if there is a body" for the method property, but since I already set the method to POST, I thought nothing of it.

Thanks for trying to help!

**Comment by Crasha** [comment]
Right, yeah I had to read it again. Thanks!

**Comment by mhart** [comment]
Going to close this – if you can post some code that I can use to reproduce this, then I'm happy to reopen
