### ISSUE TITLE
Add 'doNotEncodePath' to documentation

### ISSUE THREAD

**Issue by pbromley** [mhart/aws4#91]
I'm using this lib to encode the requests being sent to a deployed ApiGateway using service 'execute-api'

I ran into the signature is not as expected error with AWS but found the problem was that the signer seemed to be double encoding the @ symbol in the url. Specifically the issue was the @ symbol is encoded to `%40` then the `%` is encoded to `25` which becomes `%2540` in the url.

This can be avoided by using the `doNotEncodePath` option set to `true` in the request to sign object. I think this might be useful to add this option to the documentation since I only found it by looking through the source code.

E.g.
```
{
  host: 'somethingWithA',
  path: '/@in-the-path'
  service: 'execute-api', 
  doNotEncodePath: true
  ...other options
}
```

Thanks in advance

**Comment by mhart** [comment]
@pbromley @matt-lough – this library doesn't support `uri` as an option. Are you using another library to invoke `aws4`? I suspect it may be the one doing the extra encoding

**Comment by pbromley** [comment]
That's fair, I'll update my original comment. `doNotEncodePath` is still required to be set to `true` for this to work correctly against api gateway.

**Comment by mhart** [comment]
Are you making raw https requests using the Node.js http module? Or are you using another http client?

**Comment by mhart** [comment]
I've pushed out v1.9.0 that has less aggressive URL encoding for characters like `@`

I still couldn't get any signature failures with v1.8.0 – it was just encoding the path before sending, but that was being accepted fine. I think it may have been another client that was doing the double encoding.

`doNotEncodePath` isn't really intended for public use – it's only used in tests. If you're finding that you're having to use it with raw Node.js http queries, then there's probably a bug

**Comment by mhart** [comment]
Going to close this given the update I pushed out, but please reopen if you're still having problems
