### ISSUE TITLE
403 error when signing requests to api gw on custom domain from browser

### ISSUE THREAD

**Issue by cyrfer** [mhart/aws4#93]
API Gateway is responding to my requests with a 403 status code when I use `aws4` in a browser client, e.g. from localhost:3000, when calling something like:  
`GET https://my-domain.com/stage/todos`

Possibly important specifics:
* I have API Gateway methods using the built-in IAM authorizer.
* Route 53 redirects traffic from a vanity url to my API's Cloudfront URL.
* I obtain AWS credentials in the client through a Cognito OAuth flow, but I've also tried with my personal admin creds, hard-coded in the browser code running locally.
* The same creds used in the browser (both admin or cognito user) can be used in Postman to make a request to my API GW resulting in 200 status code.

I have NO problems from my **NODEJS** back-end to another API Gateway using a custom vanity URL. That code looks like this:

```javascript
const { region } = require('./config');
const URL = require('url');
const aws4 = require('aws4');
const got = require('got');

const json = {
    'content-type': 'application/json'
};

const sendRequest = (creds, url, headers=json, method='GET', body) => {
    const { host, path } = URL.parse(url, true);
    const req = {
        host,
        path,
        region,
        service: 'execute-api',
        body,
        method,
        headers,
    };

    aws4.sign(req, creds);
    return got(req);
};
```

I'm confident I am passing the same values to `aws4.sign` in the **BROWSER** as I am in my client. That code looks like this:

```javascript
import axios from 'axios';
import aws4 from 'aws4';
import {
  aws4ToAxios,
  aws4UrlParse,
} from '../lib/aws4-utils';
import { region } from './config';

const makeRequest = (creds, stageURL, route, headers={}, method='GET', body) => {
    const { host, path, protocol } = aws4UrlParse(stageURL + route);
    const req = {
      host,
      path,
      region,
      service: 'execute-api',
      method,
      body,
      headers,
    };

    aws4.sign(req, creds);
    return axios(aws4ToAxios(protocol, req));
}
```

and the helper module `aws4-utils` being:
```javascript
// axios calls the `body` by the name 'data', but aws4 calls it 'body'
// https://github.com/axios/axios#axiosconfig
export const aws4ToAxios = (protocol, r) => {
    const { body, host, path, headers, method } = r;

    debugger;
    return {
        url: protocol + '//' + host + path,
        headers,
        method,
        data: body,
    };
};

export const aws4UrlParse = url => {
    const u = new URL(url);
    return {
        host: u.host,
        path: u.pathname,
        protocol: u.protocol,
    };
};
```

I use `makeRequest` like:
```javascript
const creds = await getCredentials();
await makeRequest(creds, 'https://my-domain.com/stage', '/todos');
```

Do you know if I need to account for the browser adding [extra headers](https://github.com/axios/axios/issues/382#issuecomment-456807828) ?

Do you see the problem?

**Comment by cyrfer** [comment]
fixed a bug where `host` contained the `protocol`. still same problem.

**Comment by cyrfer** [comment]
I was able to get my browser code to work. I'll edit this with details shortly.

**Comment by andrhamm** [comment]
@cyrfer any update on this?

**Comment by cyrfer** [comment]
@andrhamm I think I only needed to make sure all the variables had values. Watch out for 'region' being undefined. I also removed the headers added from signing, but I don't know that is required.

```javascript
aws4.sign(req, creds);
delete req.headers['Host'];
delete req.headers['Content-Length'];
return axios(aws4ToAxios(protocol, req));
```
