### ISSUE TITLE
Credential must have exactly 5 slash-delimited elements

### ISSUE THREAD

**Issue by JohnMealy23** [mhart/aws4#97]
I execute `aws4.sign` as follows:
```
const {
    AccessKeyId,
    SecretAccessKey,
    SessionToken
} = getAssumedRoleCreds();

const opts = { 
    service: 'es', 
    region: awsRegion 
}

const credentials = {
    secretAccessKey: AccessKeyId,
    accessKeyId: SecretAccessKey,
    sessionToken: SessionToken
}

const { headers } = aws4.sign(opts, credentials)

esOptions = {
    node: esLocation,
    headers
}

return new Client(esOptions)
```
When sending requests, I receive the following error for AWS:
```
"Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 't10ZbafVdL59Qpp5VEaY2asds6ABWYDuXPhOp/S/20190814/us-west-2/es/aws4_request'"
```
Inspected the requests going out, the Credentials signature varies a great deal, but never meets the `keyid/date/region/service/term` spec.

Just in case it was something with the conditional `es` logic in `aws4.sign`, I've tried switching in...
```
const opts = { 
    service: 's3', 
    region: awsRegion 
}
```
... and then...
```
headers.Authorization = headers.Authorization.replace('/s3/', '/es/')
```
... but no dice.

Any idea why the Credentials format isn't matching what AWS is expecting?

**Comment by mhart** [comment]
I'm not sure what `Client` is here.

Can you create a reproduction that doesn't rely on any third-party code?

**Comment by JohnMealy23** [comment]
@mhart - thanks for getting back to me.  In this case, `Client` is the `@elastic/elasticsearch` npm module.

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html

I can set to work setting up a test case you ask for if it's really necessary, but the response I get from AWS seems to imply the request was well-formed, but troublesome in terms of the `Credentials` parameter.  

It looks like `t10ZbafVdL59Qpp5VEaY2asds6ABWYDuXPhOp/S/20190814/us-west-2/es/aws4_request` has that extra `/S/` that doesn't agree with the `keyid/date/region/service/term` signature AWS is requiring.

**Comment by JohnMealy23** [comment]
@mhart - Scratch all that.  I'm ridiculous: 
```
const credentials = {
    secretAccessKey: AccessKeyId,
    accessKeyId: SecretAccessKey,
    sessionToken: SessionToken
}
```
Off to go pawn my keyboard and join the circus.  Have a good one!

**Comment by mhart** [comment]
Ha! I didn't spot that either. Hope it works ok now 👍

**Comment by mhart** [comment]
Closing
